GET http://localhost:3000/cinema
Content-Type:application/json

###

POST http://localhost:3000/cinema
Content-Type:application/json

 {
    "name": "Yelmo cines",
    "location": "Valencia",
    "movies": ["644831bbee186edf0202b953","64483240ee186edf0202b958"]
  }

  ###

  FIND http://localhost:3000/cinema
  Content-Type:application/json
